# Generated by Django 4.0.4 on 2022-06-11 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_another_alter_book_slug_alter_book_another'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='another',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.another'),
        ),
    ]
