# Generated by Django 4.0.4 on 2022-06-12 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_address_another_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='another',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.address'),
        ),
    ]
